apps/customer/urls.py
# ./apps/customer/urls.py

from django.urls import path
from .views import VehicleListView, VehicleCreateView, VehicleUpdateView, VehicleDeleteView

app_name = 'my_customer'

urlpatterns = [
    path('vehicles/', VehicleListView.as_view(), name='vehicle_list'),
    path('vehicles/add/', VehicleCreateView.as_view(), name='vehicle_add'),
    path('vehicles/<int:pk>/edit/', VehicleUpdateView.as_view(), name='vehicle_edit'),
    path('vehicles/<int:pk>/delete/', VehicleDeleteView.as_view(), name='vehicle_delete'),
]

infoparts/urls.py
from django.apps import apps
from django.urls import include, path
from django.contrib import admin
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

    # The Django admin is not officially supported; expect breakage.
    # Nonetheless, it's often useful for debugging.

    path('admin/', admin.site.urls),
    
    path('customer/', include('apps.customer.urls', namespace='my_customer')),
    
    path('', include(apps.get_app_config('oscar').urls[0])),
    
    path('auth_accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

apps/catalogue/models.py
from django.db import models
from oscar.apps.catalogue.abstract_models import AbstractProduct

class Product(AbstractProduct):
    video_url = models.URLField(blank=True, null=True)



from oscar.apps.catalogue.models import * 

apps/customer/models.py
# ./apps/customer/models.py

from django.db import models
from oscar.apps.customer.abstract_models import *


class Vehicle(models.Model):
    MODEL_CHOICES = [
        ('model1', 'Land Rover Series I'),
        ('model2', 'Land Rover Series II'),
        ('model3', 'Land Rover Series IIA'),
        ('model4', 'Land Rover Series III'),
        ('model5', 'Land Rover Defender 90'),
        ('model6', 'Land Rover Defender 110'),
        ('model7', 'Land Rover Defender 130'),
        ('model8', 'Land Rover Discovery'),
        ('model9', 'Land Rover Discovery Sport'),
        ('model10', 'Land Rover Freelander'),
        ('model11', 'Range Rover SE'),
        ('model12', 'Range Rover HSE'),
        ('model13', 'Range Rover Autobiography'),
        ('model14', 'Range Rover SVAAutobiography'),
        ('model15', 'Range Rover Sport SE'),
        ('model16', 'Range Rover Sport HSE'),
        ('model17', 'Range Rover Sport SVR'),
        ('model18', 'Range Rover Sport AutoBiography'),
        ('model19', 'Range Rover Evoque'),
        ('model20', 'Range Rover Velar'),
    ]

    DOORS_CHOICES = [
        (3, '3 doors'),
        (5, '5 doors'),
    ]

    FUEL_TYPE_CHOICES = [
        ('gasoline', 'Gasoline'),
        ('diesel', 'Diesel'),
        ('hybrid', 'Hybrid'),
    ]

    model = models.CharField(max_length=100, choices=MODEL_CHOICES)
    number_of_doors = models.IntegerField(choices=DOORS_CHOICES)
    fuel_type = models.CharField(max_length=10, choices=FUEL_TYPE_CHOICES)
    year = models.IntegerField()
    license_plate = models.CharField(
        max_length=8, unique=True)

    def __str__(self):
        return f"{self.model} ({self.license_plate})"


class UserVehicle(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'vehicle')



from oscar.apps.customer.models import *

apps/dashboard/models.py
from oscar.apps.dashboard.models import * 

apps/partner/models.py
from django.db import models
from oscar.apps.partner.abstract_models import AbstractPartner

class Partner(AbstractPartner):    
    email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    mobile_number = models.CharField(max_length=15, blank=True, null=True)

from oscar.apps.partner.models import * 

apps/customer/forms.py
# ./apps/customer/forms.py

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import re
from .models import Vehicle, UserVehicle
from django.contrib.auth import get_user_model

User = get_user_model()

def validate_license_plate(value):
    # Check if the license plate has the correct format
     if not re.match(r'^([A-Z]{2}-\d{2}-[A-Z]{2}|\d{2}-[A-Z]{2}-\d{2}|\d{2}-\d{2}-\d{2}|[A-Z]{2}-\d{2}-\d{2}|[A-Z]{2}-[A-Z]{2}-[A-Z]{2}|\d{2}-\d{2}-[A-Z]{2})$', value):
        raise ValidationError(
            _('%(value)s is not a valid license plate'),
            params={'value': value},
        )

class VehicleForm(forms.ModelForm):
    YEAR_CHOICES = [(r,r) for r in range(1948, timezone.now().year+1)]
    year = forms.ChoiceField(choices=YEAR_CHOICES)
    license_plate = forms.CharField(validators=[validate_license_plate])
    
    class Meta:
        model = Vehicle
        fields = ['model', 'number_of_doors', 'fuel_type', 'year', 'license_plate']

class UserVehicleForm(forms.ModelForm):
    class Meta:
        model = UserVehicle
        fields = ['user', 'vehicle']
        widgets = {'user': forms.HiddenInput()}
        
from oscar.apps.customer.forms import *

apps/dashboard/partners/forms.py
from oscar.apps.dashboard.partners.forms import PartnerCreateForm as CorePartnerCreateForm

class PartnerCreateForm(CorePartnerCreateForm):
    
    class Meta(CorePartnerCreateForm.Meta):
        
        fields = ['name', 'email', 'phone_number', 'mobile_number']

apps/customer/views.py
# ./apps/customer/views.py

from django.views import View
from django.shortcuts import render, redirect
from .forms import VehicleForm, UserVehicleForm
from .models import Vehicle, UserVehicle
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class VehicleListView(View):
    def get(self, request):
        vehicles = UserVehicle.objects.filter(user=request.user)
        return render(request, 'oscar/customer/vehicles/vehicle_list.html', {'vehicles': vehicles})


@method_decorator(login_required, name='dispatch')
class VehicleCreateView(View):
    def get(self, request):
        form = VehicleForm()
        return render(request, 'oscar/customer/vehicles/vehicle_form.html', {'form': form})

    def post(self, request):
        form = VehicleForm(request.POST)
        if form.is_valid():
            vehicle = form.save()
            UserVehicle.objects.create(user=request.user, vehicle=vehicle)
            messages.success(request, 'Vehicle added successfully.')
            return redirect('my_customer:vehicle_list')  # change this line
        return render(request, 'oscar/customer/vehicles/vehicle_form.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class VehicleUpdateView(View):
    def get(self, request, pk):
        vehicle = Vehicle.objects.get(pk=pk)
        form = VehicleForm(instance=vehicle)
        return render(request, 'oscar/customer/vehicles/vehicle_form.html', {'form': form, 'is_edit': True})

    def post(self, request, pk):
        vehicle = Vehicle.objects.get(pk=pk)
        form = VehicleForm(request.POST, instance=vehicle)
        if form.is_valid():
            form.save()
            messages.success(request, 'Vehicle updated successfully.')
            return redirect('my_customer:vehicle_list')  # change this line
        return render(request, 'oscar/customer/vehicles/vehicle_form.html', {'form': form, 'is_edit': True})


@method_decorator(login_required, name='dispatch')
class VehicleDeleteView(View):
    def get(self, request, pk):
        vehicle = Vehicle.objects.get(pk=pk)
        return render(request, 'oscar/customer/vehicles/vehicle_confirm_delete.html', {'vehicle': vehicle})

    def post(self, request, pk):
        vehicle = Vehicle.objects.get(pk=pk)
        user_vehicle = UserVehicle.objects.get(user=request.user, vehicle=vehicle)
        vehicle.delete()
        user_vehicle.delete()
        messages.success(request, 'Vehicle deleted successfully.')
        return redirect('my_customer:vehicle_list')  # change this line


from oscar.apps.customer.views import *

templates/oscar/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-gb" }}" class="{% block html_class %}no-js{% endblock %}">
    <head>
        <title>{% block title %}InfoParts{{ shop_tagline }}{% endblock %}</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="{% now "jS M Y h:i" %}" />
        <meta name="description" content="{% block description %}{% endblock %}" />
        <meta name="viewport" content="{% block viewport %}width=device-width{% endblock %}" />

        {% block favicon %}
            <link rel="shortcut icon" href="{% static "img/Logo1.ico" %}" />
        {% endblock %}

        {# Block where global CSS will go. #}
        {% block styles %}{% endblock %}

        {# Additional CSS - specific to certain pages #}
        {% block extrastyles %}{% endblock %}

        {% block extrahead %}{% endblock %}

        {% block tracking %}
            {# Default to using Google analytics #}
            {% include "oscar/partials/google_analytics.html" %}
        {% endblock %}
    </head>

    <body id="{% block body_id %}default{% endblock %}" class="{% block body_class %}default{% endblock %}">
        {# Main content goes in this 'layout' block #}
        {% block layout %}{% endblock %}

        {# Scripts loaded from a CDN. #}
        {% block cdn_scripts %}
            <!-- jQuery -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
            <script>window.jQuery || document.write('<script src="{% static "oscar/js/jquery/jquery.min.js" %}"><\/script>')</script>
        {% endblock %}

        {# Local scripts #}
        {% block scripts %}
        {% endblock %}

        {# Additional JS scripts #}
        {% block extrascripts %}{% endblock %}

        {# Block for body onload functions #}
        <script>
            $(function() {
                {% block onbodyload %}{% endblock %}
            });
        </script>

        {# Page meta-data - this is populated by the 'metadata' template context processor #}
    </body>
</html>

templates/oscar/customer/login_registration.html
{% extends "oscar/customer/login_registration.html" %}
{% load i18n %}
{% load static %}
{% load socialaccount%}

{% block extrastyles%}
    <style>
        .separator {
            display: flex;
            align-items: center;
            text-align: center;
          }
          
          .separator::before,
          .separator::after {
            content: '';
            flex: 1;
            border-bottom: 1px solid #000;
          }
          
          .separator:not(:empty)::before {
            margin-right: .25em;
          }
          
          .separator:not(:empty)::after {
            margin-left: .25em;
          }
    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-6 login_form">
            <form id="login_form" action="{{ request.get_full_path }}" method="post" class="card card-body bg-light" >
                <h2>{% trans 'Log In' %}</h2>
                {% csrf_token %}
                {% include "oscar/partials/form_fields.html" with form=login_form %}
                <p><a href="{% url 'password-reset' %}">{% trans "I've forgotten my password" %}</a></p>
                <button name="login_submit" type="submit" value="Log In" class="btn btn-lg btn-primary" data-loading-text="{% trans "Logging in..." %}">{% trans 'Log In' %}</button>
            
                <div class="separator" style="margin: 20px 0px 20px;">{% trans "OR" %}</div>

                <div style="text-align: center;">
                    <a href="{% provider_login_url 'google' %}">
                        <img src="{% static 'img/web_light_sq_SI@2x.png' %}" style="width: 240px; heigth: 10px;">
                    </a>
                </div>
                <br>
                <div style="text-align: center;">
                    <a href="{% provider_login_url 'facebook' %}">
                        <img src="{% static 'img/LogInFacebook.png' %}" style="width: 240px; heigth: 10px;">
                    </a>
                </div>               
            
            </form>
        </div>
        <div class="col-sm-6 register_form">
            <form id="register_form" action="{{ request.get_full_path }}" method="post" class="card card-body bg-light">
                <h2>{% trans 'Register' %}</h2>
                {% csrf_token %}
                {% include "oscar/partials/form_fields.html" with form=registration_form %}
                <button name="registration_submit" type="submit" value="Register" class="btn btn-lg btn-primary" data-loading-text="{% trans 'Registering...' %}">{% trans 'Register' %}</button>
            </form>
        </div>
    </div>

{% endblock content %}

templates/oscar/customer/partials/standard_tabs.html
{% load i18n %}
{% load display_tags %}

<li class="nav-item">
    <a href="{% url 'customer:profile-view' %}" class="nav-link{% if active_tab == 'profile' %} active{% endif %}">{% trans "Profile" %}</a>
</li>
<li class="nav-item">
    <a href="{% url 'my_customer:vehicle_list' %}" class="nav-link{% if active_tab == 'vehicles' %} active{% endif %}">{% trans "Vehicles" %}</a>
</li>
<li class="nav-item">
    <a href="{% url 'customer:order-list' %}" class="nav-link{% if active_tab == 'orders' %} active{% endif %}">{% trans "Order History" %}</a>
</li>
<li class="nav-item">
    <a href="{% url 'customer:address-list' %}" class="nav-link{% if active_tab == 'addresses' %} active{% endif %}">{% trans "Address Book" %}</a>
</li>
<li class="nav-item">
    <a href="{% url 'customer:email-list' %}" class="nav-link{% if active_tab == 'emails' %} active{% endif %}">{% trans "Email History" %}</a>
</li>
<li class="nav-item">
    <a href="{% url 'customer:alerts-list' %}" class="nav-link{% if active_tab == 'alerts' %} active{% endif %}">{% trans "Product Alerts" %}</a>
</li>
<li class="nav-item">
    <a href="{% url 'customer:notifications-inbox' %}" class="nav-link{% if active_tab == 'notifications' %} active{% endif %}">{% trans "Notifications" %}</a>
</li>
{% iffeature 'wishlists' %}
    <li class="nav-item">
        <a href="{% url 'customer:wishlists-list' %}" class="nav-link{% if active_tab == 'wishlists' %} active{% endif %}">{% trans "Wish Lists" %}</a>
    </li>
{% endiffeature %}

templates/oscar/customer/vehicles/vehicle_confirm_delete.html
{% extends "oscar/customer/baseaccountpage.html" %}

{% load i18n %}

{% block extra_breadcrumbs %}
    <li class="breadcrumb-item">
        <a href="{% url 'my_customer:vehicle_list' %}">{% trans 'Vehicle list' %}</a>
    </li>
{% endblock %}

{% block tabcontent %}
    <h1>{% trans 'Confirm delete' %}</h1>
    <p>{% trans 'Are you sure you want to delete this vehicle?' %}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{% trans 'Yes, delete' %}</button>
        <a href="{% url 'my_customer:vehicle_list' %}" class="btn btn-secondary">{% trans 'No, go back' %}</a>
    </form>
{% endblock tabcontent %}

templates/oscar/customer/vehicles/vehicle_form.html
{% extends "oscar/customer/baseaccountpage.html" %}

{% load i18n %}

{% block extra_breadcrumbs %}
    <li class="breadcrumb-item">
        <a href="{% url 'my_customer:vehicle_list' %}">{% trans 'Vehicle list' %}</a>
    </li>
{% endblock %}

{% block tabcontent %}
    <h1>
        {% if is_edit %}
            {% trans 'Edit Vehicle' %}
        {% else %}
            {% trans 'Add a new vehicle' %}
        {% endif %}
    </h1>
    {% with form=form style='horizontal' %}
        {% include "oscar/partials/form.html" %}
    {% endwith %}
{% endblock tabcontent %}

templates/oscar/customer/vehicles/vehicle_list.html
{% extends "oscar/customer/baseaccountpage.html" %}
{% load i18n %}

{% block tabcontent %}

    {% if vehicles %}
        <table class="table table-striped table-bordered">
            <tbody>
                <tr>
                    <th>{% trans 'Vehicle' %}</th>
                    <th>{% trans 'License Plate' %}</th>
                    <th></th>
                </tr>
                {% for user_vehicle in vehicles %}
                    <tr>
                        <td>
                            <strong>{% trans 'Modelo' %}:</strong> {{ user_vehicle.vehicle.get_model_display }}<br/>
                            <strong>{% trans 'Portas' %}:</strong> {{ user_vehicle.vehicle.number_of_doors }}<br/>
                            <strong>{% trans 'Combustível' %}:</strong> {{ user_vehicle.vehicle.get_fuel_type_display }}<br/>
                            <strong>{% trans 'Ano' %}:</strong> {{ user_vehicle.vehicle.year }}
                        </td>
                        <td>
                            {{ user_vehicle.vehicle.license_plate }}
                        </td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-secondary" href="{% url 'my_customer:vehicle_edit' pk=user_vehicle.vehicle.id %}">{% trans 'Edit' %}</a>
                                <button class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"></button>
                                <div class="dropdown-menu">
                                    <a href="{% url 'my_customer:vehicle_delete' pk=user_vehicle.vehicle.id %}" class="dropdown-item">
                                        {% trans 'Delete' %}
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "oscar/partials/pagination.html" %}
    {% else %}
        <p>{% trans 'There are no vehicles in your vehicle list.' %}</p>
    {% endif %}
    <p>
        <a href="{% url 'my_customer:vehicle_add' %}" class="btn btn-primary">{% trans 'Add a new vehicle' %}</a>
    </p>
{% endblock tabcontent %}

templates/oscar/dashboard/users/detail.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} users{% endblock %}

{% block title %}{{ customer.email }} | {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:users-index' %}">{% trans "Customers" %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ customer.email }}</li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}{{ customer.email }}{% endblock %}

{% block dashboard_content %}
    <div class="row">
        {% block user_general_info %}
            <div class="col-md-12">
                <div class="table-header">
                    <h2>{% trans "General" %}</h2>
                </div>
                <table class="table table-bordered">
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <td>{{ customer.get_full_name|default:"-" }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Email" %}</th>
                        <td>{{ customer.email }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Active" %}?</th>
                        <td>
                            {{ customer.is_active|yesno:_("Yes,No") }}
                        </td>
                    </tr>
                    <tr>
                        <th>{% trans "Superuser" %}?</th>
                        <td>{{ customer.is_superuser|yesno:_("True,False") }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Staff" %}?</th>
                        <td>{{ customer.is_staff|yesno:_("True,False") }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Last login" %}</th>
                        <td>{{ customer.last_login }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Date joined" %}</th>
                        <td>{{ customer.date_joined }}</td>
                    </tr>
                    {% if customer.userrecord %}
                        {% with record=customer.userrecord %}
                            <tr>
                                <th>{% trans "Products viewed" %}</th>
                                <td>{{ record.num_product_views|default:0 }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Number of orders" %}</th>
                                <td>{{ record.num_orders|default:0 }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Number of ordered items" %}</th>
                                <td>{{ record.num_order_items|default:0 }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Total spent" %}</th>
                                <td>{{ record.total_spent|default:0|currency }}</td>
                            </tr>
                        {% endwith %}
                    {% endif %}
                    <tr>
                        <th>{% trans "Reviews written" %}</th>
                        <td>{{ customer.reviews.count }}</td>
                    </tr>
                    {% if customer.email %}
                        <tr>
                            <th>{% trans "Actions" %}</th>
                            <td>
                                <form id="password_reset_form" action="{% url 'dashboard:user-password-reset' pk=customer.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Sending...' %}">{% trans 'Send password reset email' %}</button>
                                </form>
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        {% endblock %}
    </div>
    <div class="row">
        {% block user_additional_info %}
            <div class="tabbable dashboard col-md-12">
                {% block tab_nav %}
                    <ul class="nav nav-tabs mb-0" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" href="#user_orders" data-toggle="tab">{% trans "Orders" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#user_addresses" data-toggle="tab">{% trans "Addresses" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#user_reviews" data-toggle="tab">{% trans "Reviews" %}</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#user_vehicles" data-toggle="tab">{% trans "Vehicles" %}</a>
                        </li>


                    </ul>
                {% endblock %}

                <div class="tab-content">
                    {% block user_orders %}
                        <div id="user_orders" class="tab-pane fade show active" role="tabpanel">
                            <table class="table table-striped table-bordered table-hover">
                                <caption>{% trans "Orders" %}</caption>
                                {% with orders=customer.orders.all %}
                                    {% if orders %}
                                        <tr>
                                            <th>{% trans "Order Number" %}</th>
                                            <th>{% trans "Num items" %}</th>
                                            <th>{% trans "Total value" %}</th>
                                            <th>{% trans "Date placed" %}</th>
                                            <th>{% trans "Status" %}</th>
                                            <th></th>
                                        </tr>
                                        {% for order in orders %}
                                            <tr>
                                                <td><a href="{% url 'dashboard:order-detail' order.number %}">{{ order.number }}</a></td>
                                                <td>{{ order.num_items }}</td>
                                                <td>{{ order.basket_total_incl_tax|currency }}</td>
                                                <td>{{ order.date_placed|date }}</td>
                                                <td>{{ order.status|default:"-" }}</td>
                                                <td><a href="{% url 'dashboard:order-detail' number=order.number %}" class="btn btn-info">{% trans "View" %}</a></td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <tr><td>{% trans "This customer has not placed any orders yet." %}</td></tr>
                                    {% endif %}
                                {% endwith %}
                            </table>

                        </div>
                    {% endblock %}

                    {% block user_addresses %}
                        <div id="user_addresses" class="tab-pane fade" role="tabpanel">
                            <h2>{% trans "Addresses" %}</h2>
                            <div class="row">
                                {% for address in customer.addresses.all %}

                                    <div class="col-md-3">
                                        <div class="card card-body bg-info">
                                            {% for field in address.active_address_fields %}
                                                {{ field }}<br/>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    {% if forloop.counter|divisibleby:4 %}
                                    </div>
                                    <div class="row">
                                    {% endif %}
                                {% empty %}
                                    <p>{% trans "This customer has not saved any addresses." %}</p>
                                {% endfor %}
                            </div>
                        </div>
                    {% endblock %}

                    {% block user_reviews %}
                        <div id="user_reviews" class="tab-pane fade" role="tabpanel">
                            <table class="table table-striped table-bordered table-hover">
                                <caption>{% trans "Reviews" %}</caption>
                                {% if customer.reviews.count %}
                                    <tr>
                                        <th>{% trans "Product ID" %}</th>
                                        <th>{% trans "Score" %}</th>
                                        <th>{% trans "Title" context "Product review title" %}</th>
                                        <th>{% trans "Body" %}</th>
                                        <th>{% trans "Date created" %}</th>
                                    </tr>
                                    {% for review in customer.reviews.all %}
                                        <tr>
                                            <td>{{ review.product_id }}</td>
                                            <td>{{ review.score }}</td>
                                            <td>{{ review.title }}</td>
                                            <td>{{ review.body }}</td>
                                            <td>{{ review.date_created }}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr><td>{% trans "This customer has not written any reviews yet." %}</td></tr>
                                {% endif %}
                            </table>

                        </div>
                    {% endblock %}

                    {% block user_vehicles %}
                        <div id="user_vehicles" class="tab-pane fade" role="tabpanel">
                            <h2>{% trans "Vehicles" %}</h2>
                            <table class="table table-striped table-bordered table-hover">
                                <!--<caption>{% trans "Vehicles" %}</caption>-->
                                {% with vehicles=customer.uservehicle_set.all %}
                                    {% if vehicles %}
                                        <tr>
                                            <th>{% trans "Model" %}</th>
                                            <th>{% trans "Number of Doors" %}</th>
                                            <th>{% trans "Fuel Type" %}</th>
                                            <th>{% trans "License Plate" %}</th>
                                            <th>{% trans "Year" %}</th>
                                        </tr>
                                        {% for user_vehicle in vehicles %}
                                            <tr>
                                                <td>{{ user_vehicle.vehicle.get_model_display }}</td>
                                                <td>{{ user_vehicle.vehicle.number_of_doors }}</td>
                                                <td>{{ user_vehicle.vehicle.get_fuel_type_display }}</td>
                                                <td>{{ user_vehicle.vehicle.license_plate }}</td>
                                                <td>{{ user_vehicle.vehicle.year }}</td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <tr><td>{% trans "This customer has not registered any vehicles yet." %}</td></tr>
                                    {% endif %}
                                {% endwith %}
                            </table>
                        </div>
                    {% endblock %}


                </div>
            </div>
        </div>
    {% endblock %}
{% endblock dashboard_content %}